ci: update version of rust
error: package `bumpalo v3.16.0` cannot be built because it requires
rustc 1.73.0 or newer, while the currently active rustc version is
1.72.0
Either upgrade to rustc 1.73.0 or newer, or use
cargo update -p bumpalo@3.16.0 --precise ver
where `ver` is the latest version of `bumpalo` supporting rustc 1.72.0